name: camera_utils_example
description: Demonstrates how to use the camera_utils plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  video_player: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  camera_utils:
    path: ../


flutter:

  uses-material-design: true

  assets:
  - assets/images/ic_flutter_devs_logo.png
  - assets/images/ic_no_image.png
  - assets/images/ic_play.png

        
    
    
                                      