name: camera_utils
description: Flutter plugin for capturing and picking image and videos and getting thumbnail from videos on the Android & iOS devices.
version: 0.1.7
authors:
- Deepak Nishad <deepak@aeologic.com>
- Virander <virander@aeologic.com>
homepage: https://www.aeologic.com/
documentation:
repository: https://github.com/flutter-devs/camera_utils
issue_tracker: https://github.com/flutter-devs/camera_utils/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.aeologic.camerautils
    pluginClass: CameraUtilsPlugin

