name: camera_utils
description: Flutter plugin for capturing and picking image and videos on the Android & iOS devices.
version: 0.1.1
authors:
- Deepak Nishad <deepak@aeologic.com>
- Virander <virander@aeologic.com>
homepage: https://www.flutterdevs.com
documentation: https://pub.dartlang.org/documentation/camera_utils

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.aeologic.camerautils
    pluginClass: CameraUtilsPlugin

